FROM openjdk:18-alpine

ARG kafka_version=3.0.0
ARG scala_version=2.13

LABEL org.label-schema.name="kafka" \
      org.label-schema.description="Apache Kafka" \
      org.label-schema.build-date="today" \
      org.label-schema.vcs-url="https://github.com/palmer" \
      org.label-schema.vcs-ref="1.0.0" \
      org.label-schema.version="${scala_version}_${kafka_version}" \
      org.label-schema.schema-version="1.0" \
      maintainer="palmer"

ENV KAFKA_VERSION=$kafka_version \
    SCALA_VERSION=$scala_version \
    KAFKA_HOME=/opt/kafka

ENV PATH=${PATH}:${KAFKA_HOME}/bin

COPY start-kafka.sh download-kafka.sh versions.sh /tmp/

RUN apk add --virtual=build --no-cache bash curl jq \
    && chmod a+x /tmp/*.sh \
    && mv /tmp/start-kafka.sh /tmp/versions.sh /usr/bin \
    && /tmp/download-kafka.sh \
    && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt \
    && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
    && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} ${KAFKA_HOME} \
    && rm -f -r /tmp/*

COPY overrides /opt/overrides

VOLUME ["/kafka"]

# Use "exec" form so that it runs as PID 1 (useful for graceful shutdown)
CMD ["start-kafka.sh"]
