FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:1.17-1

LABEL description="A container for event driven ansible"
LABEL software="EDA,Ansible"

LABEL maintainer="gpalmerjr@gmail.com"

WORKDIR /var/tmp

ADD https://raw.githubusercontent.com/ansible/event-driven-ansible/main/requirements.txt /var/tmp/
COPY files/requirements.txt /var/tmp/ansible_requirements.txt

RUN microdnf install python3-pip sshpass openssh-clients -y && microdnf clean all -y
RUN pip3 install -r /var/tmp/ansible_requirements.txt -r /var/tmp/requirements.txt --no-cache-dir
RUN ansible-galaxy collection install ansible.eda