FROM python:3.12.0a1-alpine

LABEL description="A container for automation development"
LABEL software="Terraform,Packer,Ansible"
LABEL maintainer="gpalmerjr@gmail.com"

ARG TERRAFORM="1.0.6"
ARG PACKER="1.7.5"

WORKDIR /var/tmp

COPY requirements.txt /var/tmp/

RUN apk add --no-cache python3 py3-pip sshpass && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make unzip curl && \
    python3 -m pip --no-cache-dir install --upgrade pip setuptools wheel && \
    python3 -m pip --no-cache-dir install azure-cli && \
    python3 -m pip --no-cache-dir install -r /var/tmp/requirements.txt && \
    curl -O -L "https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip" && \
    curl -O -L "https://releases.hashicorp.com/packer/${PACKER}/packer_${PACKER}_linux_amd64.zip" && \
    unzip -d /usr/local/bin terraform_1.0.6_linux_amd64.zip && \
    unzip -d /usr/local/bin packer_1.7.5_linux_amd64.zip && \
    rm -f *.zip && \
    apk del --purge build
