FROM python:3-alpine

LABEL description="A container for automation development"
LABEL software="Terraform,Packer,Ansible"
LABEL maintainer="gpalmerjr@gmail.com"

ARG TERRAFORM="1.4.0"
ARG PACKER="1.8.6"

WORKDIR /var/tmp

COPY requirements.txt /var/tmp/

RUN apk add --no-cache sshpass unzip curl jq && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make && \
    python3 -m pip --no-cache-dir install --upgrade pip setuptools wheel && \
    python3 -m pip --no-cache-dir install azure-cli && \
    python3 -m pip --no-cache-dir install -r /var/tmp/requirements.txt && \
    curl -O -L "https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip" && \
    curl -O -L "https://releases.hashicorp.com/packer/${PACKER}/packer_${PACKER}_linux_amd64.zip" && \
    unzip -d /usr/local/bin "terraform_${TERRAFORM}_linux_amd64.zip" && \
    unzip -d /usr/local/bin "packer_${PACKER}_linux_amd64.zip" && \
    rm -f *.zip && \
    apk del --purge build
