name: CookieCutter Build
run-name: ${{ github.actor }} is building the CookieCutter image 🚀
on: [push]
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'cookiecutter/**'

env:
  IMAGE_NAME: cookiecutter
#
jobs:
  CookieCutter-Container-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd $IMAGE_NAME
          podman build . --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: List Images
        run: |
          podman image list
      
      # - uses: anchore/sbom-action@v0
      #   with:
      #     image: "${{ env.IMAGE_NAME }}:latest"
      #     output-file: "${{ github.workspace}}/sbom.json"
      #     artifact-name: "sbom.json"
      #     format: spdx-json

      - name: List
        run: |
          podman run --rm "${{ env.IMAGE_NAME }}:latest" pip list --no-index --format=json > out.json

      - name: Get cookiecutter version
        run: |
          jq -r '.[] | select(.name=="${{ env.IMAGE_NAME }}").version' out.json



