name: CookieCutter Build
run-name: ${{ github.actor }} is building the CookieCutter image 🚀
on: [push]
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'cookiecutter/**'

env:
  IMAGE_NAME: cookiecutter
#
jobs:
  CookieCutter-Container-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd $IMAGE_NAME
          podman build . --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: List Images
        run: |
          podman image list
      
      - uses: anchore/sbom-action@v0
        with:
          image: "${{ env.IMAGE_NAME }}:latest"
          artifact-name: "sbom.json"

      - name: List
        run: |
          ls -la
          cat sbom.json

      - name: Get cookiecutter version
        run: |
          jq '.artifacts[] | select (.name == "cookiecutter").version' sbom.json



